//
//  SearchSceneInteractor.swift
//  Pulentunes
//
//  Created by Diego Alexander Salazar on 10/15/19.
//  Copyright (c) 2019 Diego Alexander Salazar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchSceneInteractorProtocol {
    func search()
}

protocol SearchSceneDataStore {
}

class SearchSceneInteractor: SearchSceneInteractorProtocol, SearchSceneDataStore {
    var presenter: SearchScenePresentationProtocol?
    var worker: SearchSceneWorker?

    func search() {
        worker = SearchSceneWorker()
        let fetchSearch = FetchSearchMedia.shared
        
        fetchSearch.search(text: "love", completion: { (result) in
            guard let results = self.worker?.transformData(result.results) else { return }
            self.presenter?.presentResults(results: results)
        }) { (error) in
            print(error)
        }
    }
}
