//
//  SearchSceneWorker.swift
//  Pulentunes
//
//  Created by Diego Alexander Salazar on 10/15/19.
//  Copyright (c) 2019 Diego Alexander Salazar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchSceneWorker {
    func transformData(_ model: [SearchModel]) -> [SearchListViewModel.Item] {
        let data: [SearchListViewModel.Item] = model.map({
            let item = SearchListViewModel.Item(title: $0.trackName,
                                                coverImage: $0.artworkUrl100,
                                                artist: $0.artistName,
                                                album: $0.collectionName)
            return item
        })
        
        return data
    }
}
