//
//  SearchScenePresenter.swift
//  Pulentunes
//
//  Created by Diego Alexander Salazar on 10/15/19.
//  Copyright (c) 2019 Diego Alexander Salazar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchScenePresentationProtocol {
    func presentResults(results: [SearchListViewModel.Item])
}

class SearchScenePresenter: SearchScenePresentationProtocol {
    weak var viewController: SearchSceneViewProtocol?

    // MARK: Present

    func presentResults(results: [SearchListViewModel.Item]) {
        viewController?.displayList(withViewModel: results)
    }
}
