//
//  SearchScenePresenter.swift
//  Pulentunes
//
//  Created by Diego Alexander Salazar on 10/15/19.
//  Copyright (c) 2019 Diego Alexander Salazar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchScenePresentationLogic {
    func presentSomething(response: SearchScene.Something.Response)
}

class SearchScenePresenter: SearchScenePresentationLogic {
    weak var viewController: SearchSceneDisplayLogic?

    // MARK: Do something

    func presentSomething(response: SearchScene.Something.Response) {
        let viewModel = SearchScene.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
