//
//  SearchScenePresenter.swift
//  Pulentunes
//
//  Created by Diego Alexander Salazar on 10/15/19.
//  Copyright (c) 2019 Diego Alexander Salazar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchScenePresentationProtocol {
    func presentSomething()
}

class SearchScenePresenter: SearchScenePresentationProtocol {
    weak var viewController: SearchSceneViewProtocol?

    // MARK: Do something

    func presentSomething() {
        //let viewModel = SearchScene.Something.ViewModel()
        //viewController?.displaySomething(viewModel: viewModel)
    }
}
