//
//  SearchSceneInteractor.swift
//  Pulentunes
//
//  Created by Diego Alexander Salazar on 10/15/19.
//  Copyright (c) 2019 Diego Alexander Salazar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchSceneBusinessLogic
{
  func doSomething(request: SearchScene.Something.Request)
}

protocol SearchSceneDataStore
{
  //var name: String { get set }
}

class SearchSceneInteractor: SearchSceneBusinessLogic, SearchSceneDataStore
{
  var presenter: SearchScenePresentationLogic?
  var worker: SearchSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchScene.Something.Request)
  {
    worker = SearchSceneWorker()
    worker?.doSomeWork()
    
    let response = SearchScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
